(() => {
	'use strict';

	const log = (msg) => console.log('[AutoSubtitles] ' + msg);
	let isRunning = false;
	let styleEl = null;
	let observer = null;

	// ───── Hide settings (once, late) ─────
	const hideSettings = () => {
		if (styleEl) return;
		styleEl = document.createElement('style');
		styleEl.id = 'autosub-hide-settings';
		styleEl.textContent = `
      .ytp-settings-button,
      .ytp-panel,
      .ytp-panel-menu,
      .ytp-popup,
      .ytp-settings-menu {
        visibility: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
        transform: translateX(-9999px) !important;
      }
    `;
		document.head.appendChild(styleEl);
		log('Settings hidden (final)');
	};

	// ───── Show settings ─────
	const showSettings = () => {
		if (styleEl?.parentNode) {
			styleEl.parentNode.removeChild(styleEl);
			styleEl = null;
		}
		log('Settings restored');
	};

	// ───── Force subtitles on ─────
	const forceSubtitlesOn = () => {
		const apply = () => {
			const video = document.querySelector('video');
			if (video?.textTracks?.[0]) {
				try { video.textTracks[0].mode = 'showing'; } catch (e) { }
			}
		};
		apply();
		const interval = setInterval(apply, 3000);
		// Auto-clear after 30s to reduce overhead
		setTimeout(() => clearInterval(interval), 30000);
	};

	// ───── Main automation ─────
	const runAutomation = () => {
		if (isRunning) return;
		isRunning = true;

		let gear = null;
		let attempts = 0;
		const maxAttempts = 50;

		const waitForGear = () => {
			gear = document.querySelector('.ytp-settings-button');
			if (!gear && ++attempts < maxAttempts) {
				return setTimeout(waitForGear, 200);
			}
			if (!gear) {
				log('Gear never found');
				isRunning = false;
				return;
			}

			log('Gear found, waiting for stable render...');

			// Wait extra time for YouTube to finish rendering controls
			setTimeout(() => {
				if (!gear.isConnected) {
					log('Gear disconnected during delay');
					isRunning = false;
					return;
				}

				// NOW hide (late, once)
				hideSettings();

				// Open settings off-screen
				gear.click();
				log('Settings opened (hidden)');

				// Wait for subtitles menu
				waitForSubtitlesMenu();
			}, 600); // Critical delay
		};

		const waitForSubtitlesMenu = () => {
			let attempts = 0;
			const maxAttempts = 30;

			const check = () => {
				const item = Array.from(document.querySelectorAll('.ytp-menuitem'))
					.find(i => /subtitles|cc/i.test(i.textContent || ''));

				if (item && item.isConnected) {
					// SUBTITLES EXIST → NOW safe to hide gear
					hideSettings();  // ← MOVED HERE
					item.click();
					log('Subtitles menu found → hiding gear & clicking');
					setTimeout(selectAutoGenerated, 200);
				} else if (++attempts < maxAttempts) {
					setTimeout(check, 100);
				} else {
					// NO SUBTITLES → DO NOT HIDE GEAR
					log('No subtitles menu → keeping gear visible');
					cleanup();  // ← Still restore (in case anything was touched), but nothing was hidden
				}
			};
			check();
		};

		const selectAutoGenerated = () => {
			const items = document.querySelectorAll('.ytp-menuitem');
			const auto = Array.from(items).find(i => {
				const txt = (i.textContent || '').toLowerCase();
				return txt.includes('auto-generated') || txt.includes('automatic');
			});

			if (auto && auto.isConnected) {
				auto.click();
				log('Auto-subtitles enabled');
			} else {
				log('No auto-generated option');
			}

			cleanup();
		};

		const cleanup = () => {
			setTimeout(() => {
				// Close menu if still open
				if (gear?.isConnected && gear.getAttribute('aria-expanded') === 'true') {
					gear.click();
				}
				forceSubtitlesOn();
				showSettings();
				isRunning = false;
			}, 300);
		};

		// Start
		waitForGear();
	};

	// ───── Start on player ready ─────
	const start = () => {
		const player = document.querySelector('.html5-video-player');
		const video = document.querySelector('video');
		if (player && video && video.readyState >= 1) {
			log('Player ready, starting automation...');
			setTimeout(runAutomation, 800);
		} else {
			setTimeout(start, 500);
		}
	};

	// ───── Handle navigation ─────
	const handleNavigate = () => {
		if (observer) observer.disconnect();
		log('Navigate finish');
		setTimeout(start, 1000);
	};

	document.addEventListener('yt-navigate-finish', handleNavigate);

	// Optional: MutationObserver fallback for dynamic loads
	observer = new MutationObserver((mutations) => {
		if (!isRunning && document.querySelector('video')?.readyState >= 1) {
			const player = document.querySelector('.html5-video-player');
			if (player) {
				observer.disconnect();
				setTimeout(start, 800);
			}
		}
	});

	observer.observe(document.body, { childList: true, subtree: true });

	// Initial check
	if (document.readyState === 'complete') {
		setTimeout(start, 1000);
	}

})();