(() => {
  'use strict';

  const log = (msg) => console.log('[AutoSubtitles] ' + msg);
  const POLL = 250;
  const TIMEOUT = 20_000;

  let isRunning = false;
  let styleEl = null;

  // Hide UI
  const hideUI = () => {
    if (styleEl) return;
    styleEl = document.createElement('style');
    styleEl.textContent = `
      .ytp-settings-button,
      .ytp-panel,
      .ytp-panel-menu,
      .ytp-popup {
        transform: translateX(-9999px) !important;
        visibility: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
      }
      video { visibility: visible !important; }
    `;
    document.head.appendChild(styleEl);
    log('UI hidden');
  };

  const showUI = () => {
    if (styleEl?.parentNode) {
      styleEl.parentNode.removeChild(styleEl);
      styleEl = null;
      log('UI restored');
    }
  };

  // Main automation
  const runAutomation = () => {
    if (isRunning) return;
    isRunning = true;
    let startTime = Date.now();
    let gearBtn = null;

    const waitForGear = () => {
      gearBtn = document.querySelector('.ytp-settings-button');
      if (gearBtn) {
        hideUI();
        setTimeout(() => {
          gearBtn.click();
          log('Settings opened');
          waitForSubtitlesMenu();
        }, 100);
      } else if (Date.now() - startTime < TIMEOUT) {
        setTimeout(waitForGear, POLL);
      } else {
        log('Timeout: Settings button not found');
        cleanup();
      }
    };

    const waitForSubtitlesMenu = () => {
      const item = Array.from(document.querySelectorAll('.ytp-menuitem'))
        .find(i => /subtitles|cc/i.test(i.textContent.trim()));
      if (item) {
        item.click();
        log('Subtitles menu clicked');
        setTimeout(selectAutoGenerated, 200);
      } else if (Date.now() - startTime < TIMEOUT) {
        setTimeout(waitForSubtitlesMenu, POLL);
      } else {
        log('Timeout: Subtitles menu item not found');
        cleanup();
      }
    };

    const selectAutoGenerated = () => {
      const items = document.querySelectorAll('.ytp-menuitem');
      const autoGen = Array.from(items).find(i => {
        const txt = (i.textContent || '').toLowerCase();
        return txt.includes('auto-generated') || txt.includes('automatic');
      });

      if (autoGen) {
        autoGen.click();
        log(`Enabled: ${autoGen.textContent.trim()}`);
      } else {
        log('No auto-generated subtitles found');
      }
      cleanup();
    };

    const cleanup = () => {
      setTimeout(() => {
        const gear = document.querySelector('.ytp-settings-button');
        if (gear?.getAttribute('aria-expanded') === 'true') {
          gear.click();
        }
        forceSubtitlesOn();
        showUI();
        isRunning = false;
      }, 300);
    };

    const forceSubtitlesOn = () => {
      const apply = () => {
        const video = document.querySelector('video');
        if (video?.textTracks?.[0]) {
          try { video.textTracks[0].mode = 'showing'; } catch(e) {}
        }
      };
      apply();
      setInterval(apply, 3000);
    };

    waitForGear();
  };

  // Start on yt-navigate-finish (works for both hard refresh & click)
  const startOnNavigate = () => {
    // Wait for player container
    const waitForPlayer = setInterval(() => {
      const player = document.querySelector('.html5-video-player');
      const video = document.querySelector('video');
      if (player && video) {
        clearInterval(waitForPlayer);
        log('Player ready – starting automation');
        setTimeout(runAutomation, 500); // small delay for stability
      }
    }, 300);

    setTimeout(() => clearInterval(waitForPlayer), 15000);
  };

  // Listen to YouTube's official navigation event
  document.addEventListener('yt-navigate-finish', () => {
    log('yt-navigate-finish detected');
    startOnNavigate();
  });

  // Also run immediately if already on watch page
  if (location.pathname.startsWith('/watch')) {
    log('Initial load on /watch – starting');
    startOnNavigate();
  }

})();