(() => {
  'use strict';

  const log = (msg) => console.log('[AutoSubtitles] ' + msg);
  const POLL = 200;
  const TIMEOUT = 25_000;
  let startTime = Date.now();
  let gearBtn = null;
  let styleEl = null;

  // ───── Hide UI during automation ─────
  const hideUI = () => {
    styleEl = document.createElement('style');
    styleEl.id = 'auto-subtitles-hide';
    styleEl.textContent = `
      /* Move player controls off-screen */
      .ytp-settings-button,
      .ytp-panel,
      .ytp-panel-menu,
      .ytp-popup {
        transform: translateX(-9999px) !important;
        visibility: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
      }
      /* Keep video visible */
      video { visibility: visible !important; }
    `;
    document.head.appendChild(styleEl);
    log('UI hidden for silent automation');
  };

  // ───── Restore UI ─────
  const showUI = () => {
    if (styleEl && styleEl.parentNode) {
      styleEl.parentNode.removeChild(styleEl);
      log('UI restored');
    }
  };

  // ───── 1. Wait for gear → click silently ─────
  const waitForGear = () => {
    gearBtn = document.querySelector('.ytp-settings-button');
    if (gearBtn) {
      hideUI();
      setTimeout(() => {
        gearBtn.click();
        log('Settings opened (off-screen)');
        waitForSubtitlesItem();
      }, 50);
    } else if (Date.now() - startTime < TIMEOUT) {
      setTimeout(waitForGear, POLL);
    } else {
      log('Timeout: gear not found');
      showUI();
    }
  };

  // ───── 2. Wait for "Subtitles" item → click ─────
  const waitForSubtitlesItem = () => {
    const panel = document.querySelector('.ytp-panel-menu');
    if (!panel) {
      setTimeout(waitForSubtitlesItem, POLL);
      return;
    }

    const observer = new MutationObserver(() => {
      const item = Array.from(panel.querySelectorAll('.ytp-menuitem'))
        .find(i => /subtitles|cc/i.test(i.textContent.trim()));
      if (item) {
        observer.disconnect();
        item.click();
        log('Subtitles submenu opened (silent)');
        setTimeout(selectAutoGenerated, 180);
      }
    });

    observer.observe(panel, { childList: true, subtree: true });

    // Fallback poll
    const fallback = setInterval(() => {
      const item = Array.from(panel.querySelectorAll('.ytp-menuitem'))
        .find(i => /subtitles|cc/i.test(i.textContent.trim()));
      if (item) {
        clearInterval(fallback);
        observer.disconnect();
        item.click();
        setTimeout(selectAutoGenerated, 180);
      }
    }, POLL);
  };

  // ───── 3. Select first "auto-generated" ─────
  const selectAutoGenerated = () => {
    const menu = document.querySelector('.ytp-panel-menu');
    if (!menu) {
      cleanup();
      return;
    }

    const items = menu.querySelectorAll('.ytp-menuitem');
    const autoGen = Array.from(items).find(i => {
      const txt = (i.getAttribute('aria-label') || i.textContent).toLowerCase();
      return txt.includes('auto-generated') || txt.includes('automatic');
    });

    if (autoGen) {
      autoGen.click();
      log(`Selected: ${autoGen.textContent.trim()}`);
    } else {
      log('No auto-generated subtitles found');
    }

    cleanup();
  };

  // ───── 4. Close menus + restore UI + force track ─────
  const cleanup = () => {
    setTimeout(() => {
      const gear = document.querySelector('.ytp-settings-button');
      if (gear && gear.getAttribute('aria-expanded') === 'true') {
        gear.click();
      }
      forceSubtitlesVisible();
      showUI();
    }, 250);
  };

  // ───── 5. Force subtitles visible forever ─────
  const forceSubtitlesVisible = () => {
    const apply = () => {
      const video = document.querySelector('video');
      if (!video) return;
      const track = video.textTracks?.[0];
      if (track && track.mode !== 'showing') {
        track.mode = 'showing';
      }
    };
    apply();
    setInterval(apply, 3000);
  };

  // ───── Start when player exists ─────
  const init = () => {
    const player = document.querySelector('.html5-video-player') ||
                   document.querySelector('ytd-watch-flexy');
    if (player) {
      log('Player ready – starting silent subtitle activation');
      waitForGear();
    } else {
      setTimeout(init, 500);
    }
  };

  init();
})();